object = [	POWERDATA.NAME,POWERDATA.OBJECT,POWERDATA.COST,POWERDATA.SLOTCOOLDOWN,POWERDATA.SLOTSPRITE,
			POWERDATA.PLACEMENTONGRID,POWERDATA.PLACEMENTONPIECE,
			POWERDATA.DESCRIPTION];
//power_database()
