object = [	PIECEDATA.NAME,PIECEDATA.OBJECT,PIECEDATA.SPRITE,PIECEDATA.SLOTSPRITE,
			PIECEDATA.PLACECOST,PIECEDATA.SLOTCOOLDOWN,PIECEDATA.MOVECOOLDOWN,PIECEDATA.MOVECOST,PIECEDATA.HP,
			PIECEDATA.MOVES, // first row ONLY_ATTACK; second row ONLY_MOVE; third row BOTH. Numbers in strings are affectd by team & toggling variables
			PIECEDATA.PLACEMENTONGRID,PIECEDATA.PLACEMENTONPIECE,
			PIECEDATA.CLASS,PIECEDATA.TYPE,
			PIECEDATA.BRIEFDESCRIPTION,
			PIECEDATA.DESCRIPTION];
//piece_database()