bullet_part = part_type_create();
part_type_shape(bullet_part, pt_shape_pixel);
part_type_size(bullet_part, 1, 1, 0, 0);
part_type_scale(bullet_part, 2, 2);
part_type_colour3(bullet_part, #FFFFFF, #FFFFFF, #FFFFFF);
part_type_alpha3(bullet_part,1, .5, 0);
part_type_speed(bullet_part, 0, 0, 0, 0);
part_type_direction(bullet_part, 0, 0, 0, 0);
part_type_gravity(bullet_part, 0, 0);
part_type_orientation(bullet_part, 0, 0, 0, 0, 1);
part_type_blend(bullet_part, false);